languages = {
	"Arabic": "ar",
	"Bulgarian": "bg",
	"Catalan": "ca",
	"Chinese Simplified": "zh-CHS",
	"Chinese Traditional": "zh-CHT",
	"Czech": "cs",
	"Danish": "da",	
	"Dutch": "nl",
	"English": "en",
	"Estonian": "et",
	"Finnish": "fi",
	"French": "fr",
	"German": "de",
	"Greek": "el",
	"Haitian Creole": "ht",
	"Hebrew": "he",
	"Hindi": "hi",
	"Hmong Daw": "mww",
	"Hungarian": "hu",
	"Indonesian": "id",
	"Italian": "it",
	"Japanese": "ja",
	"Klingon": "tlh",
	"Klingon (pIqaD)":"tlh-Qaak",
	"Korean": "ko",
	"Latvian": "lv",
	"Lithuanian": "lt",
	"Malay": "ms",
	"Maltese": "mt",
	"Norwegian": "no",
	"Persian": "fa",
	"Polish": "pl",
	"Portuguese": "pt",
	"Romanian": "ro",
	"Russian": "ru",
	"Slovak": "sk",
	"Slovenian": "sl",
	"Spanish": "es",
	"Swedish": "sv",
	"Thai": "th",
	"Turkish": "tr",
	"Ukrainian": "uk",
	"Urdu": "ur",
	"Vietnamese": "vi",
	"Welsh": "cy"
}